<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "pits_downloadcenter"
 *
 * Auto generated by Extension Builder 2015-02-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched! 
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Download Center',
	'description' => 'Download Center Sponsored by TNT-Graphics AG',
	'category' => 'plugin',
	'author' => 'Hoja MA, Sivakumar S',
	'author_email' => 'hoja.ma@pitsolutions.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0 - 7.1.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);